from AccessControl import allow_module

from Products.Archetypes import atapi

from Products.PloneServicesCenter import PSCMessageFactory as _

# BBB pake the ATCountry widget unpickleable
import sys
import Products.Archetypes
from Products.Archetypes import Widget
sys.modules['Products.ATCountryWidget'] = Products.Archetypes
sys.modules['Products.ATCountryWidget.Widget'] = Widget
Widget.CountryWidget = Widget.SelectionWidget

module = "Products.PloneServicesCenter.content.country"
allow_module(module)

countries = {
    _(u"Europe (Western)"): atapi.DisplayList([
        ("ad", _(u"Andorra")),
        ("at", _(u"Austria")),
        ("be", _(u"Belgium")),
        ("dk", _(u"Denmark")),
        ("fo", _(u"Faroe Islands")),
        ("fi", _(u"Finland")),
        ("fr", _(u"France")),
        ("de", _(u"Germany")),
        ("gi", _(u"Gibraltar")),
        ("gl", _(u"Greenland")),
        ("is", _(u"Iceland")),
        ("ie", _(u"Ireland")),
        ("it", _(u"Italy")),
        ("li", _(u"Liechtenstein")),
        ("lu", _(u"Luxembourg")),
        ("mt", _(u"Malta")),
        ("mc", _(u"Monaco")),
        ("nl", _(u"Netherlands")),
        ("no", _(u"Norway")),
        ("pt", _(u"Portugal")),
        ("sm", _(u"San Marino")),
        ("es", _(u"Spain")),
        ("sj", _(u"Svalbard And Jan Mayen Islands")),
        ("se", _(u"Sweden")),
        ("ch", _(u"Switzerland")),
        ("gb", _(u"United Kingdom")),
        ("va", _(u"Vatican City State (Holy See)")),
        ]),
    _(u"Europe (Central)"): atapi.DisplayList([
        ("al", _(u"Albania")),
        ("ba", _(u"Bosnia And Herzegowina")),
        ("bg", _(u"Bulgaria")),
        ("hr", _(u"Croatia (Local Name: Hrvatska)")),
        ("cz", _(u"Czech Republic")),
        ("gr", _(u"Greece")),
        ("hu", _(u"Hungary")),
        ("mk", _(u"Macedonia, The Former Yugoslav Republic Of")),
        ("pl", _(u"Poland")),
        ("ro", _(u"Romania")),
        ("cs", _(u"Serbia")),
        ("sk", _(u"Slovakia (Slovak Republic)")),
        ("si", _(u"Slovenia")),
        ]),
    _(u"Europe (Eastern)"): atapi.DisplayList([
        ("am", _(u"Armenia")),
        ("az", _(u"Azerbaijan")),
        ("by", _(u"Belarus")),
        ("ee", _(u"Estonia")),
        ("ge", _(u"Georgia")),
        ("lv", _(u"Latvia")),
        ("lt", _(u"Lithuania")),
        ("md", _(u"Moldova, Republic Of")),
        ("ru", _(u"Russian Federation")),
        ("ua", _(u"Ukraine")),
        ]),
    _(u"North America"): atapi.DisplayList([
        ("ca", _(u"Canada")),
        ("mx", _(u"Mexico")),
        ("pm", _(u"St. Pierre And Miquelon")),
        ("us", _(u"United States")),
        ("um", _(u"United States Minor Outlying Islands")),
        ]),
    _(u"Central America"): atapi.DisplayList([
        ("bz", _(u"Belize")),
        ("cr", _(u"Costa Rica")),
        ("sv", _(u"El Salvador")),
        ("gt", _(u"Guatemala")),
        ("hn", _(u"Honduras")),
        ("ni", _(u"Nicaragua")),
        ("pa", _(u"Panama")),
        ]),
    _(u"South America"): atapi.DisplayList([
        ("ar", _(u"Argentina")),
        ("bo", _(u"Bolivia")),
        ("br", _(u"Brazil")),
        ("cl", _(u"Chile")),
        ("co", _(u"Colombia")),
        ("ec", _(u"Ecuador")),
        ("fk", _(u"Falkland Islands (Malvinas)")),
        ("gf", _(u"French Guiana")),
        ("gy", _(u"Guyana")),
        ("py", _(u"Paraguay")),
        ("pe", _(u"Peru")),
        ("gs", _(u"South Georgia And The South Sandwich Islands")),
        ("sr", _(u"Suriname")),
        ("uy", _(u"Uruguay")),
        ("ve", _(u"Venezuela")),
        ]),
    _(u"Middle East"): atapi.DisplayList([
        ("bh", _(u"Bahrain")),
        ("cy", _(u"Cyprus")),
        ("ir", _(u"Iran (Islamic Republic Of)")),
        ("iq", _(u"Iraq")),
        ("il", _(u"Israel")),
        ("jo", _(u"Jordan")),
        ("kw", _(u"Kuwait")),
        ("lb", _(u"Lebanon")),
        ("om", _(u"Oman")),
        ("qa", _(u"Qatar")),
        ("sa", _(u"Saudi Arabia")),
        ("sy", _(u"Syrian Arab Republic")),
        ("tr", _(u"Turkey")),
        ("ae", _(u"United Arab Emirates")),
        ("ye", _(u"Yemen")),
        ]),
    _(u"Central Asia"): atapi.DisplayList([
        ("io", _(u"British Indian Ocean Territory")),
        ("kz", _(u"Kazakhstan")),
        ("kg", _(u"Kyrgyzstan")),
        ("tj", _(u"Tajikistan")),
        ("tm", _(u"Turkmenistan")),
        ("uz", _(u"Uzbekistan")),
        ]),
    _(u"South Asia"): atapi.DisplayList([
        ("af", _(u"Afghanistan")),
        ("bd", _(u"Bangladesh")),
        ("bt", _(u"Bhutan")),
        ("in", _(u"India")),
        ("mv", _(u"Maldives")),
        ("np", _(u"Nepal")),
        ("pk", _(u"Pakistan")),
        ("lk", _(u"Sri Lanka")),
        ]),
    _(u"South East Asia"): atapi.DisplayList([
        ("bn", _(u"Brunei Darussalam")),
        ("kh", _(u"Cambodia")),
        ("id", _(u"Indonesia")),
        ("la", _(u"Lao People's Democratic Republic")),
        ("my", _(u"Malaysia")),
        ("mm", _(u"Myanmar")),
        ("ph", _(u"Philippines")),
        ("sg", _(u"Singapore")),
        ("th", _(u"Thailand")),
        ("tl", _(u"Timor-Leste")),
        ("vn", _(u"Viet Nam")),
        ]),
    _(u"North East Asia"): atapi.DisplayList([
        ("cn", _(u"China")),
        ("hk", _(u"Hong Kong")),
        ("jp", _(u"Japan")),
        ("kp", _(u"Korea, Democratic People's Republic Of")),
        ("kr", _(u"Korea, Republic Of")),
        ("mo", _(u"Macau")),
        ("mn", _(u"Mongolia")),
        ("tw", _(u"Taiwan")),
        ]),
    _(u"Australasia"): atapi.DisplayList([
        ("as", _(u"American Samoa")),
        ("aq", _(u"Antarctica")),
        ("au", _(u"Australia")),
        ("cx", _(u"Christmas Island")),
        ("cc", _(u"Cocos (Keeling) Islands")),
        ("ck", _(u"Cook Islands")),
        ("fj", _(u"Fiji")),
        ("pf", _(u"French Polynesia")),
        ("gu", _(u"Guam")),
        ("hm", _(u"Heard And Mc Donald Islands")),
        ("ki", _(u"Kiribati")),
        ("mh", _(u"Marshall Islands")),
        ("fm", _(u"Micronesia, Federated States Of")),
        ("nr", _(u"Nauru")),
        ("nc", _(u"New Caledonia")),
        ("nz", _(u"New Zealand")),
        ("nu", _(u"Niue")),
        ("nf", _(u"Norfolk Island")),
        ("mp", _(u"Northern Mariana Islands")),
        ("pw", _(u"Palau")),
        ("pg", _(u"Papua New Guinea")),
        ("pn", _(u"Pitcairn")),
        ("ws", _(u"Samoa")),
        ("sb", _(u"Solomon Islands")),
        ("tk", _(u"Tokelau")),
        ("to", _(u"Tonga")),
        ("tv", _(u"Tuvalu")),
        ("vu", _(u"Vanuatu")),
        ("wf", _(u"Wallis And Futuna Islands")),
        ]),
    _(u"Caribbean"): atapi.DisplayList([
        ("ai", _(u"Anguilla")),
        ("ag", _(u"Antigua And Barbuda")),
        ("aw", _(u"Aruba")),
        ("bs", _(u"Bahamas")),
        ("bb", _(u"Barbados")),
        ("bm", _(u"Bermuda")),
        ("ky", _(u"Cayman Islands")),
        ("cu", _(u"Cuba")),
        ("dm", _(u"Dominica")),
        ("do", _(u"Dominican Republic")),
        ("gd", _(u"Grenada")),
        ("gp", _(u"Guadeloupe")),
        ("ht", _(u"Haiti")),
        ("jm", _(u"Jamaica")),
        ("mq", _(u"Martinique")),
        ("ms", _(u"Montserrat")),
        ("an", _(u"Netherlands Antilles")),
        ("pr", _(u"Puerto Rico")),
        ("kn", _(u"Saint Kitts And Nevis")),
        ("lc", _(u"Saint Lucia")),
        ("vc", _(u"Saint Vincent And The Grenadines")),
        ("tt", _(u"Trinidad And Tobago")),
        ("tc", _(u"Turks And Caicos Islands")),
        ("vg", _(u"Virgin Islands (British)")),
        ("vi", _(u"Virgin Islands (U.S.)")),
        ]),
    _(u"Africa"): atapi.DisplayList([
        ("dz", _(u"Algeria")),
        ("ao", _(u"Angola")),
        ("bj", _(u"Benin")),
        ("bw", _(u"Botswana")),
        ("bv", _(u"Bouvet Island")),
        ("bf", _(u"Burkina Faso")),
        ("bi", _(u"Burundi")),
        ("cm", _(u"Cameroon")),
        ("cv", _(u"Cape Verde")),
        ("cf", _(u"Central African Republic")),
        ("td", _(u"Chad")),
        ("km", _(u"Comoros")),
        ("cd", _(u"Congo, Democratic Republic Of (Was Zaire)")),
        ("cg", _(u"Congo, People's Republic Of")),
        ("ci", _(u"Cote D'ivoire")),
        ("dj", _(u"Djibouti")),
        ("eg", _(u"Egypt")),
        ("gq", _(u"Equatorial Guinea")),
        ("er", _(u"Eritrea")),
        ("et", _(u"Ethiopia")),
        ("tf", _(u"French Southern Territories")),
        ("ga", _(u"Gabon")),
        ("gm", _(u"Gambia")),
        ("gh", _(u"Ghana")),
        ("gn", _(u"Guinea")),
        ("gw", _(u"Guinea-Bissau")),
        ("ke", _(u"Kenya")),
        ("ls", _(u"Lesotho")),
        ("lr", _(u"Liberia")),
        ("ly", _(u"Libyan Arab Jamahiriya")),
        ("mg", _(u"Madagascar")),
        ("mw", _(u"Malawi")),
        ("ml", _(u"Mali")),
        ("mr", _(u"Mauritania")),
        ("mu", _(u"Mauritius")),
        ("yt", _(u"Mayotte")),
        ("ma", _(u"Morocco")),
        ("mz", _(u"Mozambique")),
        ("na", _(u"Namibia")),
        ("ne", _(u"Niger")),
        ("ng", _(u"Nigeria")),
        ("re", _(u"Reunion")),
        ("rw", _(u"Rwanda")),
        ("st", _(u"Sao Tome And Principe")),
        ("sn", _(u"Senegal")),
        ("sc", _(u"Seychelles")),
        ("sl", _(u"Sierra Leone")),
        ("so", _(u"Somalia")),
        ("za", _(u"South Africa")),
        ("sh", _(u"St. Helena")),
        ("sd", _(u"Sudan")),
        ("sz", _(u"Swaziland")),
        ("tz", _(u"Tanzania, United Republic Of")),
        ("tg", _(u"Togo")),
        ("tn", _(u"Tunisia")),
        ("ug", _(u"Uganda")),
        ("eh", _(u"Western Sahara")),
        ("zm", _(u"Zambia")),
        ("zw", _(u"Zimbabwe")),
        ]),
    }

vocab = countries.values()[0]
for dl in countries.values()[1:]:
    vocab += dl
